### ISSUE TITLE
Add haveNoText() and containText() to should()

### ISSUE THREAD

**Issue by ElenaShev** [estuold/teasy-simple#21]
It will be good to add some new methods to should() interface: haveNoText() and containText(String text). At the moment we are using TeasyElement.should().haveText("") and assertTrue(TeasyElement.getText.contains(text)) and its not great

**Comment by ElenaShev** [comment]
may we somehow change haveText() logic? it will be great if it could return "value" attribute, because now in such situation (see picture) .should().haveText(pro6) returns false.
![image](https://user-images.githubusercontent.com/41183692/42691862-65ed417a-86b2-11e8-84af-3e9bcaa35ffd.png)

**Comment by estuold** [comment]
Added in 1.0.11 version
