### ISSUE TITLE
Cannot launch test using Gecko in mac platform

### ISSUE THREAD

**Issue by mosadchiy** [estuold/teasy-simple#30]
Everything is fine with Firefox 58.0 and Windows platform, but looks like gecko doesn't work in mac

**Comment by vefimofff** [comment]
1. We would we very happy to receive some more details what you faced during the run you did. If you have any steps to reproduce, logs, stack traces - please provide here.
2. As I see FF 58 is not the latest on. If possible please also try it on FF 61 on Mac.

**Comment by vefimofff** [comment]
I also found a potential problem, that we set the following
        options.setCapability("platform", Platform.WINDOWS);
to FirefoxOptions
This might be the reason of issues. I am going to fix this.

**Comment by vefimofff** [comment]
Although... we do the same for FireFox and it seems to work. Anyway should be fixed

**Comment by vefimofff** [comment]
https://github.com/SeleniumHQ/selenium/wiki/Grid-Platforms . based on this - the abovemetioned looks like a bug.

**Comment by estuold** [comment]
Fixed in 1.0.12
